dev-webmvc-dotnet/Models/ErrorViewModel.cs
using System;

namespace dev_webmvc_dotnet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

dev-webmvc-dotnet/Models/SendReports.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dev_webmvc_dotnet.Models
{
    public class SendReports
    {
        public Request Request { get; set; }

    }

    public partial class Request
    {
        public Properties SMS { get; set; }
        public Properties Email { get; set; }
    }

    public partial class Properties
    {
        public bool enabled { get; set; }
        public string to { get; set; }
        public string from { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
    }
}

dev-webmvc-dotnet/Models/StepFuncRequest.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dev_webmvc_dotnet.Models
{
    public class StepFuncRequest
    {
        [JsonProperty("input")]
        public string input { get; set; }

        [JsonProperty("stateMachineArn")]
        public string stateMachineArn { get; set; }
    }
}

dev-webmvc-dotnet/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dev_webmvc_dotnet.Models
{
    public class Weather
    {
        public string Location { get; set; }
        public string Time { get; set; }
        public string Temperature { get; set; }
        public string Icon { get; set; }
        public string Condition { get; set; }
        public string WindSpeed { get; set; }
        public string Humidity { get; set; }
    }
}

dev-webmvc-dotnet/Controllers/HomeController.cs
using dev_webmvc_dotnet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace dev_webmvc_dotnet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

dev-webmvc-dotnet/Controllers/SendReportsController.cs
using dev_webmvc_dotnet.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dev_webmvc_dotnet.Controllers
{
    public class SendReportsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Send(Weather weather)
        {
            //Set SendReports Object
            string body = $"The weather is currently {weather.Condition} with temperature of {weather.Temperature} C. Humidity is at {weather.Humidity}% and wind speed is {weather.WindSpeed} km/h.";
            SendReports sendReports = new SendReports();
            sendReports.Request = new Request();
            sendReports.Request.SMS = new Properties();
            sendReports.Request.SMS.enabled = true;
            sendReports.Request.SMS.from = "+353858203415";
            sendReports.Request.SMS.to = "+353858203415";
            sendReports.Request.SMS.body = body;

            sendReports.Request.Email = new Properties();
            sendReports.Request.Email.enabled = true;
            sendReports.Request.Email.to = "croke@live.com";
            sendReports.Request.Email.from = "conorcrokeproject@gmail.com";
            sendReports.Request.Email.subject = "Show Me the Weather!";
            sendReports.Request.Email.body = body;
            
            //Set Stepfunction body request
            var input = JsonConvert.SerializeObject(sendReports);
            var bodyRequest = new StepFuncRequest();
            bodyRequest.input = input;
            bodyRequest.stateMachineArn = "arn:aws:states:eu-west-1:092431187700:stateMachine:SendReports";
            var bodySerialize = JsonConvert.SerializeObject(bodyRequest);

            var client = new RestClient("https://zsqq8tbfm1.execute-api.eu-west-1.amazonaws.com/dev");
            var request = new RestRequest(Method.POST);
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("application/json", bodySerialize, ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            
            return View();
        }
    }
}

dev-webmvc-dotnet/Controllers/WeatherController.cs
using dev_webmvc_dotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dev_webmvc_dotnet.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IConfiguration _config;
        public WeatherController(IConfiguration config)
        {
            _config = config;
        }

        // GET: WeatherController
        public ActionResult Index()
        {
            Weather weather = new Weather();
            weather.Location = "-";
            var dt = DateTime.Now;
            weather.Time = dt.ToString("HH:mm");
            weather.Temperature = "-";
            weather.Icon = "-";
            weather.Condition = "-";
            weather.WindSpeed = "-";
            weather.Humidity = "-";
            return View(weather);
        }

        public async Task<IActionResult> GetWeather(string longitude, string latitude)
        {
            var apiUrl = _config.GetValue<string>("APIUrl");

            var url = $"{apiUrl}weather?longitude={longitude}&latitude={latitude}";
            var client = new RestClient(url);
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            var weather = JsonConvert.DeserializeObject<Weather>(response.Content);

            int index = weather.Temperature.IndexOf(".");
            if (index > 0)
            {
                weather.Temperature = weather.Temperature.Substring(0, index); 
            }
            
            weather.Icon = $"http://openweathermap.org/img/wn/{weather.Icon}@2x.png";

            var dt = DateTime.Now;
            weather.Time = dt.ToString("HH:mm");


            return PartialView("_WeatherInfo", weather);
        }
    }
}

dev-webmvc-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dev-webmvc-dotnet/Views/SendReports/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

dev-webmvc-dotnet/Views/SendReports/Send.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

dev-webmvc-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dev_webmvc_dotnet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*&copy; 2021 - dev_webmvc_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
</body>
</html>

dev-webmvc-dotnet/Views/Shared/_WeatherInfo.cshtml
@model dev_webmvc_dotnet.Models.Weather


<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-md-4 col-sm-12 col-xs-12">
            <div class="card p-4">
                <div class="d-flex">
                    <h6 class="flex-grow-1">@Html.DisplayName(Model.Location)</h6>
                    <h6>@Html.DisplayName(Model.Time)</h6>
                </div>
                <div class="d-flex flex-column temp mt-5 mb-3">
                    <h1 class="mb-0 font-weight-bold" id="heading"> @Html.DisplayName(Model.Temperature)° C </h1> <span class="small grey">@Html.DisplayName(Model.Condition)</span>
                </div>
                <div class="d-flex">
                    <div class="temp-details flex-grow-1">
                        </br>
                        <p class="my-1"> <img src="https://i.imgur.com/B9kqOzp.png" height="17px"> <span> @Html.DisplayName(Model.WindSpeed) km/h </span> </p>
                        <p class="my-1"> <i class="fa fa-tint mr-2" aria-hidden="true"></i> <span> @Html.DisplayName(Model.Humidity)% </span> </p>
                    </div>
                    <div> <img src="@Url.Content(Model.Icon)" width="100px"> </div>
                </div>
            </div>
        </div>
    </div>
</div>

</br>


<button id='SendReports' type="button" class="btn btn-light mx-auto d-block btn-lg">Receive Weather by SMS and Email.</button>

<div class="modal fade" id="getCodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"> Please Enter your Phone Number and Email Address</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body" id="getCode" style="word-wrap:break-word;">
                <form id="smsEmail">
                    <div class="form-group">
                        <label for="emailLabel">Email address</label>
                        <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="smsLabel">Phone Number</label>
                        <input class="form-control" id="smsInput" placeholder="Enter phone number">
                    </div>
                    <button id="Send" class="btn btn-primary">Send</button>
                    @*<input id="Send" type="button" class="btn btn-primary" value="Send">*@
                </form>
            </div>
        </div>
    </div>
</div>



<form id="weather">
    @Html.HiddenFor(m => m.Condition)
    @Html.HiddenFor(m => m.Humidity)
    @Html.HiddenFor(m => m.Icon)
    @Html.HiddenFor(m => m.Location)
    @Html.HiddenFor(m => m.Temperature)
    @Html.HiddenFor(m => m.Time)
    @Html.HiddenFor(m => m.WindSpeed)
</form>

<script>

    $('#SendReports').click(function () {


        $("#getCodeModal").modal('show');

    });

    $('#Send').click(function () {


        //$("#getCodeModal").modal('show');


        var x = $('#weather').serializeArray();
        var indexed_array = {};

        $.map(x, function (n, i) {
            indexed_array[n['name']] = n['value'];
        });

        console.log(indexed_array);

        $.ajax({
            url: '@Url.Action("Send","SendReports")',
            data: indexed_array,
            success: function (data) {
            },
            error: function () {
            }
        });
    });





</script>

dev-webmvc-dotnet/Views/Weather/Index.cshtml
@model dev_webmvc_dotnet.Models.Weather

<head>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap">




    <style>

        html,
        body {
            height: 100%;
            font-family: 'Marcellus', serif
        }

        * {
            padding: 0px;
            margin: 0px
        }

        body {
            background-color: #a5a5b1;
            display: grid;
            place-items: center
        }

        .card {
            background-color: #ffffff;
            border-radius: 50px;
            color: #6f707d;
            font-family: 'Marcellus', serif
        }

        #heading {
            font-size: 55px;
            color: #2b304d
        }

        .temp {
            place-items: center
        }

        .temp-details > p > span,
        .grey {
            color: #a3acc1;
            font-size: 12px
        }

        .fa {
            color: #a5a5b1
        }

        *:focus {
            outline: none
        }
    </style>
</head>





<body>

    @*<p>Click the button to get your coordinates.</p>

        <button onclick="getLocation()">Try It</button>

        <p id="location"></p>*@


    <button type="button" class="btn btn-light mx-auto d-block btn-lg" onclick="getLocation()">Show Me the Weather!</button>

    </br>

    <div id="display"></div>









</body>

<script>


        function getLocation() {
          if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(getWeather);
          } else {
              alert("Geolocation is not supported by this browser.");
          }
        }

    function getWeather(position) {
        $.ajax({
            url: '@Url.Action("GetWeather","Weather")',
            data: { 'latitude': position.coords.latitude, 'longitude': position.coords.longitude},
            success: function (data) {
                $('#display').html(data);
            },
            error: function () {
                $("#display").html("ERROR");
            }
        });
    }

    
</script>